import axios from 'axios';
import { onAuthStateChanged, signInWithPopup, signOut } from 'firebase/auth';
import { collection, doc, setDoc, query } from 'firebase/firestore';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { useAuthState } from 'react-firebase-hooks/auth';
import { useCollectionData } from 'react-firebase-hooks/firestore';

import { auth, db, provider } from '../firebase';
export default function Home() {
  const [user, setUser] = useState();
  const [value, setValue] = useState('');
  const q = query(collection(db, 'user'));
  const [values, loading, error, snapshot] = useCollectionData(q);
  const signUser = () => {
    signInWithPopup(auth, provider)
      .then(async (result) => {
        const { user } = result;
        const userRef = doc(db, 'user', user.uid);
        await setDoc(userRef, {
          user: user.displayName,
          email: user.email,
          uid: user.uid,
          photoURL: user.photoURL,
        });
        console.log(user);
      })
      .catch((error) => {});
  };
  useEffect(() => {
    onAuthStateChanged(auth, (user) => {
      if (user) {
        setUser(user);
      }
    });
  }, []);
  useEffect(() => {
    if (values) {
      return;
    }
  }, [values]);
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div onClick={() => signUser()} className="bg-blue-500  px-10 py-3">
        sign in
      </div>
      <div onClick={() => signOut(auth)} className="bg-red-500  px-10 py-3">
        log out
      </div>
      <div>
        <span>User: </span>
        <span>{user?.displayName}</span>
      </div>
      <div className="py-3 bg-amber-500">Friend?</div>
      <div className="py-3 bg-cyan-500">Request?</div>
      <div>
        <input
          type="text"
          placeholder="search ..."
          value={value}
          onChange={(e) => setValue(e.target.value)}
          className="bg-gray-200 px-5 py-2 outline-none w-full"
        />
      </div>
    </div>
  );
}

// export function getServerSideProps(context) {
//   onAuthStateChanged(auth, (user) => {
//     if (user) {
//       user = user;
//       const uid = user.uid;
//     } else {
//     }
//   });
//   return {
//     props: {
//       user: user,
//     },
//   };
// }
